"""
Centralized Database Schema for FauxSSH.
This file serves as the source of truth for both SQLite and Postgres backends.
"""

# Table definitions: { table_name: { column_name: type, ... } }
# Types are abstracted: TEXT, INTEGER, TIMESTAMP, BOOLEAN, REAL
TABLE_SCHEMAS = {
    "sessions": {
        "session_id": "TEXT PRIMARY KEY",
        "remote_ip": "TEXT",
        "username": "TEXT",
        "password": "TEXT",
        "start_time": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
        "end_time": "TIMESTAMP",
        "client_version": "TEXT",
        "protocol": "TEXT DEFAULT 'ssh'",
        "summary": "TEXT",
        "risk_score": "INTEGER",
        "fingerprint": "TEXT",
    },
    "interactions": {
        "id": "SERIAL_PRIMARY_KEY",  # Abstracted for SERIAL (PG) / AUTOINCREMENT (SQLite)
        "session_id": "TEXT REFERENCES sessions(session_id)",
        "timestamp": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
        "cwd": "TEXT",
        "command": "TEXT",
        "response": "TEXT",
        "source": "TEXT",
        "request_md5": "TEXT",
        "response_md5": "TEXT",
        "response_head": "TEXT",
        "response_size": "INTEGER",
        "duration_ms": "INTEGER",
    },
    "auth_events": {
        "id": "SERIAL_PRIMARY_KEY",
        "timestamp": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
        "client_ip": "TEXT",
        "username": "TEXT",
        "auth_method": "TEXT",
        "auth_data": "TEXT",
        "success": "BOOLEAN",
        "client_version": "TEXT",
        "fingerprint": "TEXT",
        "protocol": "TEXT DEFAULT 'ssh'",
    },
    "global_filesystem": {
        "path": "TEXT PRIMARY KEY",
        "parent_path": "TEXT",
        "type": "TEXT",
        "metadata": "TEXT",
        "content": "TEXT",
        "created_at": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
    },
    "user_filesystem": {
        "ip": "TEXT",
        "username": "TEXT",
        "path": "TEXT",
        "parent_path": "TEXT",
        "type": "TEXT",
        "metadata": "TEXT",
        "content": "TEXT",
        "created_at": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
        "last_accessed": "TIMESTAMP",
        "is_deleted": "BOOLEAN DEFAULT FALSE",
        "PRIMARY_KEY": ["ip", "username", "path"],
    },
    "command_analysis": {
        "command_hash": "TEXT PRIMARY KEY",
        "command_text": "TEXT",
        "activity_type": "TEXT",
        "stage": "TEXT",
        "risk_score": "INTEGER",
        "explanation": "TEXT",
        "analyzed_at": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
    },
    "llm_usage": {
        "id": "SERIAL_PRIMARY_KEY",
        "ip": "TEXT NOT NULL",
        "timestamp": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
        "source": "TEXT DEFAULT 'http'",
    },
    "universal_cache": {
        "cache_key": "TEXT PRIMARY KEY",
        "service": "TEXT",
        "version": "INTEGER DEFAULT 1",
        "input_text": "TEXT",
        "input_hash": "TEXT",
        "output_text": "TEXT",
        "output_hash": "TEXT",
        "output_size": "INTEGER",
        "is_binary": "BOOLEAN DEFAULT FALSE",
        "risk_score": "INTEGER",
        "attack_stage": "TEXT",
        "explanation": "TEXT",
        "metadata": "TEXT",
        "hit_count": "INTEGER DEFAULT 0",
        "last_hit_at": "TIMESTAMP",
        "expires_at": "TIMESTAMP",
        "created_at": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
        "updated_at": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
    },
    "universal_cache": {
        "cache_key": "TEXT PRIMARY KEY",
        "service": "TEXT",
        "version": "INTEGER DEFAULT 1",
        "input_text": "TEXT",
        "input_hash": "TEXT",
        "output_text": "TEXT",
        "output_hash": "TEXT",
        "output_size": "INTEGER",
        "is_binary": "BOOLEAN DEFAULT FALSE",
        "risk_score": "INTEGER",
        "attack_stage": "TEXT",
        "explanation": "TEXT",
        "metadata": "TEXT",
        "hit_count": "INTEGER DEFAULT 0",
        "last_hit_at": "TIMESTAMP",
        "expires_at": "TIMESTAMP",
        "created_at": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
        "updated_at": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
    },
    "ip_intelligence": {
        "ip": "TEXT PRIMARY KEY",
        "hostname": "TEXT",
        "city": "TEXT",
        "country": "TEXT",
        "isp": "TEXT",
        "org": "TEXT",
        "asn": "TEXT",
        "network_type": "TEXT",
        "latitude": "REAL",
        "longitude": "REAL",
        "first_seen": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
        "last_seen": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
        "enriched": "BOOLEAN DEFAULT FALSE",
        "raw_data": "TEXT",
        "abuse_tags": "TEXT DEFAULT '[]'",
    },
    "malicious_payloads": {
        "id": "SERIAL_PRIMARY_KEY",
        "url": "TEXT",
        "url_hash": "TEXT UNIQUE",
        "session_id": "TEXT",
        "ip": "TEXT",
        "timestamp": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
        "method": "TEXT",
        "user_agent": "TEXT",
        "command_text": "TEXT",
        "status": "TEXT DEFAULT 'pending'",
        "analysis_stage": "TEXT DEFAULT 'Downloading'",
        "payload_md5": "TEXT",
        "payload_size": "INTEGER",
        "file_path": "TEXT",
        "retry_count": "INTEGER DEFAULT 0",
        "error_message": "TEXT",
        "vt_last_scanned": "TIMESTAMP",
        "vt_scan_id": "TEXT",
        "snippet": "TEXT",
        "content": "TEXT",
        "is_binary": "BOOLEAN DEFAULT FALSE",
    },
    "payload_analysis": {
        "payload_md5": "TEXT PRIMARY KEY",
        "virustotal_result": "TEXT",
        "risk_score": "INTEGER",
        "analysis_summary": "TEXT",
        "vt_last_scanned": "TIMESTAMP",
        "payload_size": "INTEGER",
        "file_path": "TEXT",
        "analyzed_at": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
    },
    "payload_requests": {
        "id": "SERIAL_PRIMARY_KEY",
        "payload_id": "INTEGER REFERENCES malicious_payloads(id)",
        "ip": "TEXT",
        "session_id": "TEXT",
        "timestamp": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
    },
    "api_usage": {
        "id": "SERIAL_PRIMARY_KEY",
        "service": "TEXT NOT NULL",
        "identifier": "TEXT NOT NULL",
        "timestamp": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
    },
    "session_summaries_cache": {
        "chain_hash": "TEXT PRIMARY KEY",
        "summary": "TEXT",
        "risk_score": "INTEGER",
        "created_at": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
    },
    "email_mailboxes": {
        "id": "SERIAL_PRIMARY_KEY",
        "ip": "TEXT",
        "username": "TEXT",
        "name": "TEXT",
        "uid_next": "INTEGER DEFAULT 1",
        "uid_validity": "INTEGER",
        "metadata": "TEXT",
        "created_at": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
    },
    "email_messages": {
        "id": "SERIAL_PRIMARY_KEY",
        "ip": "TEXT",
        "username": "TEXT",
        "mailbox_id": "INTEGER REFERENCES email_mailboxes(id)",
        "uid": "INTEGER",
        "internal_date": "TIMESTAMP",
        "flags": "TEXT",
        "size": "INTEGER",
        "header_content": "TEXT",
        "body_content": "TEXT",
        "template_path": "TEXT",
        "payload_id": "INTEGER REFERENCES malicious_payloads(id)",
        "is_deleted": "BOOLEAN DEFAULT FALSE",
        "created_at": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
        "last_accessed": "TIMESTAMP",
    },
}

# Index definitions: [ (table, column, index_name), ... ]
INDEXES = [
    ("sessions", "start_time", "idx_sessions_start"),
    ("sessions", "remote_ip", "idx_sessions_ip"),
    ("interactions", "session_id", "idx_interactions_session"),
    ("interactions", "timestamp", "idx_interactions_ts"),
    ("interactions", "request_md5", "idx_interactions_md5"),
    ("global_filesystem", "parent_path", "idx_parent"),
    ("user_filesystem", ["ip", "username", "parent_path"], "idx_user_parent"),
    ("llm_usage", ["ip", "timestamp"], "idx_llm_usage_ip_time"),
    ("ip_intelligence", ["enriched", "last_seen"], "idx_ip_intel_enriched"),
    ("malicious_payloads", "status", "idx_payload_status"),
    ("malicious_payloads", "payload_md5", "idx_payload_md5"),
    ("payload_requests", "payload_id", "idx_payload_req_pid"),
    ("universal_cache", "service", "idx_ucache_service"),
    ("universal_cache", "expires_at", "idx_ucache_expiry"),
    ("api_usage", ["service", "identifier", "timestamp"], "idx_api_usage_svc_time"),
    ("payload_analysis", "analyzed_at", "idx_payload_analysis_ts"),
    ("email_mailboxes", ["ip", "username"], "idx_email_mailbox_user"),
    ("email_messages", ["mailbox_id", "uid"], "idx_email_msg_uid"),
    ("email_messages", ["ip", "username", "is_deleted"], "idx_email_msg_user"),
]

# Tables to be automatically dropped during sync_db_schema (Redundant/Legacy)
ORPHAN_TABLES = [
    "command_cache",
    "llm_response_cache",
    "requested_urls",
]
