[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fauxssh"
version = "0.1.003"
description = "A GenAI-powered SSH Honeypot"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
  {name = "Royans Tharakan", email = "royans@gmail.com"}
]
dependencies = [
    "paramiko",
    "requests",
    "python-dotenv",
    "pyzmq"
]

[project.scripts]
fauxssh = "ssh_honeypot.server:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["ssh_honeypot*"]

[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | personas
)/
'''

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--maxfail=5"
testpaths = [
    "tests",
]
