import datetime
import random
from ssh_honeypot.handlers.base import BaseHandler

try:
    from ssh_honeypot.core.logging_setup import log
except ImportError:
    from ssh_honeypot.core.logging_setup import log

try:
    from ssh_honeypot.core.config import config
except ImportError:
    from ssh_honeypot.core.config import config

import time


class SystemHandler(BaseHandler):
    def __init__(self, db, llm):
        super().__init__(db, llm)
        # Dynamic Filesystems from Persona or Defaults
        self.FILESYSTEMS = config.get("persona", "filesystems")
        if not self.FILESYSTEMS:
            self.FILESYSTEMS = [
                {
                    "fs": "/dev/sda1",
                    "mount": "/",
                    "size": "40G",
                    "used": "8.2G",
                    "avail": "30G",
                    "use": "22%",
                    "type": "ext4",
                },
                {
                    "fs": "udev",
                    "mount": "/dev",
                    "size": "3.9G",
                    "used": "0",
                    "avail": "3.9G",
                    "use": "0%",
                    "type": "devtmpfs",
                },
                {
                    "fs": "tmpfs",
                    "mount": "/run",
                    "size": "796M",
                    "used": "1.2M",
                    "avail": "795M",
                    "use": "1%",
                    "type": "tmpfs",
                },
            ]

        # Static File Registry for Persona Consistency (Dynamic from Config)
        k_rel = config.get("persona", "kernel_release") or "5.10.0-21-cloud-amd64"
        k_ver = (
            config.get("persona", "kernel_version")
            or "#1 SMP Debian 5.10.162-1 (2023-01-21)"
        )
        d_ver = config.get("persona", "distro_version_id") or "11"
        d_pretty = (
            config.get("persona", "distro_pretty_name")
            or "Debian GNU/Linux 11 (bullseye)"
        )
        d_version_text = config.get("persona", "distro_version") or "11 (bullseye)"

        self.STATIC_FILES = {}

        self.DYNAMIC_FILES = {
            "/proc/uptime": self.generate_proc_uptime,
            "/proc/cpuinfo": self.generate_proc_cpuinfo,
            "/proc/version": self.generate_proc_version,
            "/etc/hostname": self.generate_etc_hostname,
            "/etc/resolv.conf": self.generate_etc_resolv_conf,
        }

    def _get_uptime_seconds(self):
        # Base uptime: ~14 days (1209600s) + jitter
        # We use a deterministic base + time of day to simulated a continuously running server
        # without effective reboots unless we want to reset.
        # But for 'uptime' command consistency, we just need it to be consistent within a short window?
        # Simpler: Just make it look like it's been up 14 days + however many hours/seconds since start of day

        base_days = 14
        base_seconds = 1209600

        now = datetime.datetime.now()
        # Add seconds since midnight + jitter
        seconds_today = (
            now - now.replace(hour=0, minute=0, second=0, microsecond=0)
        ).total_seconds()

        total_uptime = base_seconds + seconds_today
        idle_time = (
            total_uptime * 95
        )  # Mostly idle (192 cores means lots of idle time sum)

        return total_uptime, idle_time

    def generate_proc_uptime(self):
        up, idle = self._get_uptime_seconds()
        return f"{up:.2f} {idle:.2f}\n"

    def generate_proc_version(self):
        # Linux version 5.10.0-21-cloud-amd64 (debian-kernel@lists.debian.org) (gcc (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP Debian 5.10.162-1 (2023-01-21)
        return "Linux version 5.10.0-21-cloud-amd64 (debian-kernel@lists.debian.org) (gcc (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP Debian 5.10.162-1 (2023-01-21)\n"

    def generate_etc_hostname(self):
        h = (
            config.get("persona", "hostname")
            or config.get("server", "hostname")
            or "npc-main-server-01"
        )
        return f"{h}\n"

    def generate_etc_resolv_conf(self):
        # Realistic resolv.conf
        return """# Generated by NetworkManager
search internal.cloud
nameserver 8.8.8.8
nameserver 8.8.4.4
"""

    def generate_proc_cpuinfo(self):
        # Hardware context from persona
        hw = config.get("persona", "hardware") or {}
        cpu_model = hw.get("cpu_info") or "AMD EPYC 9654 96-Core Processor"

        # Determine core count (naive parse or default 192)
        import re

        cpus = 192
        if "vCPU" in cpu_model:
            try:
                cpus = int(re.search(r"(\d+)", cpu_model).group(1))
            except:
                pass

        out = []
        for i in range(cpus):
            out.append(f"processor\t: {i}")
            out.append(
                "vendor_id\t: AuthenticAMD"
                if "AMD" in cpu_model
                else "vendor_id\t: GenuineIntel"
            )
            out.append("model name\t: " + cpu_model)
            out.append("cpu MHz\t\t: 2400.000")
            out.append("cache size\t: 1024 KB")
            out.append(f"physical id\t: 0")
            out.append(f"siblings\t: {cpus}")
            out.append(f"core id\t\t: {i}")
            out.append(f"cpu cores\t: {cpus}")
            out.append("")
        return "\n".join(out)

    def get_dynamic_file(self, path):
        if path in self.DYNAMIC_FILES:
            return self.DYNAMIC_FILES[path]()
        return None

    def handle_lscpu(self, cmd, context):
        hw = config.get("persona", "hardware") or {}
        cpu_model = hw.get("cpu_info") or "AMD EPYC 9654 96-Core Processor"
        import re

        cpus = 192
        if "vCPU" in cpu_model:
            try:
                cpus = int(re.search(r"(\d+)", cpu_model).group(1))
            except:
                pass

        out = f"""Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          {cpus}
On-line CPU(s) list:             0-{cpus-1}
Vendor ID:                       {"AuthenticAMD" if "AMD" in cpu_model else "GenuineIntel"}
Model name:                      {cpu_model}
CPU MHz:                         2400.000
"""
        return out, {}, {"source": "handler", "cached": False}

    def handle_lspci(self, cmd, context):
        # Realistic NVIDIA H100 output + standard system
        out = """00:00.0 Host bridge: Intel Corporation 440FX - 82441FX PMC [Natoma] (rev 02)
00:01.0 ISA bridge: Intel Corporation 82371SB PIIX3 ISA [Natoma/Triton II]
00:01.3 Bridge: Intel Corporation 82371AB/EB/MB PIIX4 ACPI (rev 01)
00:02.0 VGA compatible controller: Cirrus Logic GD 5446
00:03.0 VGA compatible controller: NVIDIA Corporation H100 PCIe [Hopper] (rev a1)
00:04.0 Ethernet controller: Red Hat, Inc. Virtio network device
00:05.0 Communication controller: Red Hat, Inc. Virtio console
00:06.0 SCSI storage controller: Red Hat, Inc. Virtio block device
00:07.0 Unclassified device [00ff]: Red Hat, Inc. Virtio memory balloon
10:00.0 Non-Volatile memory controller: Amazon.com, Inc. NVMe SSD Controller (rev 01)
"""
        return out, {}, {"source": "handler", "cached": False}

    def handle_dmidecode(self, cmd, context):
        # Usually requires root (except for help/version or some flags? no usually root)
        if context.get("user") != "root":
            if "2>/dev/null" in cmd:
                return "", {}, {"source": "handler", "cached": False}
            return (
                "Permission denied\n",
                {},
                {"source": "handler", "cached": False},
            )

        # HW Info from Persona
        hw = config.get("persona", "hardware") or {}
        sys_info = config.get("persona", "system") or {}

        manufacturer = sys_info.get("manufacturer") or "Dell Inc."
        product = sys_info.get("product_name") or "PowerEdge R740"
        serial = sys_info.get("serial_number") or f"SN-{random.randint(100000, 999999)}"

        if "-s processor-version" in cmd or "--string processor-version" in cmd:
            proc_ver = (
                sys_info.get("processor_version")
                or hw.get("cpu_info")
                or "Intel(R) Xeon(R) Platinum 8480+"
            )
            return (
                f"{proc_ver}\n",
                {},
                {"source": "handler", "cached": False},
            )

        out = f"""# dmidecode 3.3
Getting SMBIOS data from sysfs.
SMBIOS 2.8 present.

Handle 0x0100, DMI type 1, 27 bytes
System Information
	Manufacturer: {manufacturer}
	Product Name: {product}
	Version: Not Specified
	Serial Number: {serial}
	UUID: {random.randint(1000,9999)}-{random.randint(1000,9999)}-{random.randint(1000,9999)}
	Wake-up Type: Power Switch
	SKU Number: Not Specified
	Family: Not Specified

Handle 0x2000, DMI type 32, 11 bytes
System Boot Information
	Status: No errors detected
"""
        return out, {}, {"source": "handler", "cached": False}

    def handle_last(self, cmd, context):
        # Realistic last output
        user = context.get("user", "root")
        ip = context.get("client_ip", "1.2.3.4")
        now = datetime.datetime.now()
        cur_str = now.strftime("%a %b %d %H:%M")

        # Fake history
        out = []
        out.append(f"{user:<8} pts/0        {ip:<16} {cur_str}   still logged in")
        # Add some previous fake logins
        out.append(
            f"root     pts/1        192.168.1.100    Tue Oct 10 12:00 - 13:00  (01:00)"
        )
        out.append(
            f"admin    pts/0        10.0.0.50        Mon Oct  9 09:30 - 10:15  (00:45)"
        )
        out.append(
            f"reboot   system boot  5.10.0-21-cloud  Mon Oct  9 09:00   still running"
        )

        return "\n".join(out) + "\n", {}, {"source": "handler", "cached": False}

    def handle_hostname(self, cmd, context):
        # Use persona hostname if available
        # Structure is persona -> system -> hostname
        sys_conf = config.get("persona", "system") or {}
        h = (
            sys_conf.get("hostname")
            or config.get("server", "hostname")
            or "npc-main-server-01"
        )

        # Parse basic args
        parts = cmd.split()
        if len(parts) > 1:
            if parts[1].startswith("-"):
                # -f, -i, etc. Just ignore or return standard
                if "i" in parts[1]:
                    return (
                        f"{context.get('honeypot_ip', '127.0.0.1')}\n",
                        {},
                        {"source": "handler", "cached": False},
                    )
            else:
                # Attempt to set hostname -> Permission denied (unless root)
                if context.get("user") != "root":
                    if "2>/dev/null" in cmd:
                        return (
                            "",
                            {},
                            {"source": "handler", "cached": False},
                        )
                    return (
                        f"hostname: you must be root to change the host name\n",
                        {},
                        {"source": "handler", "cached": False},
                    )
                else:
                    # Fake set success (no persistence)
                    return "", {}, {"source": "handler", "cached": False}

        return (
            f"{h}\n",
            {},
            {"source": "handler", "cached": False},
        )

    def handle_uname(self, cmd, context):
        # Default: Linux
        kernel_name = "Linux"
        sys_conf = config.get("persona", "system") or {}
        nodename = (
            sys_conf.get("hostname")
            or config.get("server", "hostname")
            or "npc-main-server-01"
        )

        kernel_release = "5.10.0-21-cloud-amd64"
        kernel_version = "#1 SMP Debian 5.10.162-1 (2023-01-21)"
        machine = "x86_64"
        processor = "x86_64"
        hardware_platform = "x86_64"
        os_name = "GNU/Linux"

        parts = cmd.split()
        flags = set()
        for p in parts[1:]:
            if p.startswith("-"):
                for char in p[1:]:
                    flags.add(char)

        # If no flags, default is -s (Kernel name)
        if not flags:
            return f"{kernel_name}\n", {}, {"source": "handler", "cached": False}

        if "a" in flags or "all" in flags:  # -a is --all
            return (
                f"{kernel_name} {nodename} {kernel_release} {kernel_version} {machine} {os_name}\n",
                {},
                {"source": "handler", "cached": False},
            )

        out = []
        if "s" in flags:
            out.append(kernel_name)
        if "n" in flags:
            out.append(nodename)
        if "r" in flags:
            out.append(kernel_release)
        if "v" in flags:
            out.append(kernel_version)
        if "m" in flags:
            out.append(machine)
        if "p" in flags:
            out.append(processor)
        if "i" in flags:
            out.append(hardware_platform)
        if "o" in flags:
            out.append(os_name)

        if not out:  # Default is -s
            return f"{kernel_name}\n", {}, {"source": "handler", "cached": False}

        return (
            " ".join(out) + "\n",
            {},
            {"source": "handler", "cached": False},
        )

    def handle_uptime(self, cmd, context):
        now_dt = datetime.datetime.now()
        now_str = now_dt.strftime("%H:%M:%S")

        # Calculate human friendly uptime from our consistent source
        total_seconds, _ = self._get_uptime_seconds()

        days = int(total_seconds // 86400)
        rem = total_seconds % 86400
        hours = int(rem // 3600)
        minutes = int((rem % 3600) // 60)

        # Randomize load slightly to look alive
        l1 = round(random.uniform(0.01, 0.20), 2)
        l5 = round(random.uniform(0.01, 0.15), 2)
        l15 = round(random.uniform(0.00, 0.10), 2)

        # Format: 17:05:01 up 14 days,  7:22,  2 users,  load average: 0.12, 0.08, 0.02
        return (
            f" {now_str} up {days} days, {hours}:{minutes:02d},  1 user,  load average: {l1:.2f}, {l5:.2f}, {l15:.2f}\n",
            {},
            {"source": "handler", "cached": False},
        )

    def handle_ifconfig(self, cmd, context):
        hp_ip = context.get("honeypot_ip", "192.168.1.55")
        out = f"""eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet {hp_ip}  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::20c:29ff:fe1a:2b3c  prefixlen 64  scopeid 0x20<link>
        ether 00:0c:29:1a:2b:3c  txqueuelen 1000  (Ethernet)
        RX packets 23412  bytes 14502312 (13.8 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 19821  bytes 3421901 (3.2 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 4  bytes 240 (240.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 4  bytes 240 (240.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
"""
        return out, {}, {"source": "handler", "cached": False}

    def _get_ram_info(self):
        hw = config.get("persona", "hardware") or {}
        mem_str = hw.get("memory") or "8GB"

        # Simple parser for "8GB", "256GB" -> KB
        total = 8124220
        import re

        match = re.search(r"(\d+)\s*(GB|MB)", mem_str, re.I)
        if match:
            val = int(match.group(1))
            unit = match.group(2).upper()
            if unit == "GB":
                total = val * 1024 * 1024
            else:
                total = val * 1024

        used = int(total * random.uniform(0.15, 0.40))
        free = int(total * random.uniform(0.10, 0.30))
        buff = total - used - free
        return total, used, free, buff

    def handle_free(self, cmd, context):
        total, used, free, buff = self._get_ram_info()
        return (
            f"""              total        used        free      shared  buff/cache   available
Mem:        {total}     {used}     {free}       14200     {buff}     {int(free*1.5)}
Swap:       2097148           0     2097148
""",
            {},
            {"source": "handler", "cached": False},
        )

    def handle_df(self, cmd, context):
        try:
            out = ["Filesystem      Size  Used Avail Use% Mounted on"]
            for disk in self.FILESYSTEMS:
                out.append(
                    f"{disk['fs']:<12} {disk['size']:>5} {disk['used']:>5} {disk['avail']:>5} {disk['use']:>4} {disk['mount']}"
                )
            return (
                "\n".join(out) + "\n",
                {},
                {"source": "handler", "cached": False},
            )
        except Exception as e:
            log.error(f"[ERROR] handle_df failed: {e}")
            return (
                f"Internal Error: {e}\n",
                {},
                {"source": "handler", "cached": False},
            )

    def handle_mount(self, cmd, context):
        out = []
        for disk in self.FILESYSTEMS:
            out.append(
                f"{disk['fs']} on {disk['mount']} type {disk['type']} (rw,relatime)"
            )
        out.append("proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)")
        out.append("sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)")
        return "\n".join(out) + "\n", {}, {"source": "handler", "cached": False}

    def handle_netstat(self, cmd, context):
        client_ip = context.get("client_ip", "10.0.0.2")
        hp_ip = context.get("honeypot_ip", "192.168.1.55")
        out = f"""Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN     
tcp        0    232 {hp_ip}:22            {client_ip}:54321         ESTABLISHED
udp        0      0 0.0.0.0:68              0.0.0.0:*                          
"""
        return out, {}, {"source": "handler", "cached": False}

    def handle_nproc(self, cmd, context):
        hw = config.get("persona", "hardware") or {}
        cpu_model = hw.get("cpu_info") or "AMD EPYC 9654 96-Core Processor"
        import re

        cpus = 192
        if "vCPU" in cpu_model:
            try:
                cpus = int(re.search(r"(\d+)", cpu_model).group(1))
            except:
                pass
        return (
            f"{cpus}\n",
            {},
            {"source": "handler", "cached": False},
        )

    def get_static_file(self, path):
        """Returns static content for specific system files if defined."""
        return self.STATIC_FILES.get(path)
